sudo: false
language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
  - "4"
  - "5"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - npm install standard
  - standard
script:
  - npm install istanbul
  - istanbul cover ./node_modules/.bin/_mocha --report lcovonly
after_script:
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls